config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :tokens
  resources :devices

  root 'tokens#index'
  namespace 'api' do
    resources :devices, only: [] do
      collection do 
        get 'add_device'
      end
    end
  end

end

app/models/device.rb
class Device < ActiveRecord::Base
	belongs_to :token
end

app/models/token.rb
class Token < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/api/devices_controller.rb
module Api
	class DevicesController < ApplicationController
	  respond_to :json

	  # def index
	  # 	puts 'swdew'
	  # end
	  
	  def add_device
	  	token = Token.find_by(token_name: params[:token_name])
	  	if token.present?
	  		device = Device.new(device_params)
	  		device.token = token 
  	    device.save
	  		render json: {message: "Znaleziono token", device: device}
	  	else
	  		render json: {message: "Nie znaleziono tokenu", params: params}
	  	end
	  end
		private
	  def device_params
	    params.permit(:date, :sensor, :value, :window)
	  end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :authenticate_user!
  
  protect_from_forgery with: :exception
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  def index
    # @q = Device.search(params[:q])
    # @devices = @q.result(distinct: true)  	
  	@devices = Device.all
  	# p @devices

    respond_to do |format|
      format.html
      format.js
    end
  end

  def destroy
    @device = Device.find(params[:id])
    @device.destroy
 
    redirect_to devices_path
  end  
end

app/controllers/tokens_controller.rb
class TokensController < ApplicationController
  def index 
    # @q = Token.search(params[:q])
    # @tokens = @q.result(distinct: true)
    @tokens = Token.all
  end

  def new
    @token = Token.new
  end 

  def create
  	@token = Token.new(token_params)
 
  	@token.save
  	redirect_to tokens_path
  end

  def edit
    @token = Token.find(params[:id])
  end

  def update
    @token = Token.find(params[:id])
 
    if @token.update(token_params)
      redirect_to tokens_path
    else
      render 'edit'
    end
  end

  def destroy
    @token = Token.find(params[:id])
    @token.destroy
 
    redirect_to tokens_path
  end

  private
    def token_params
      params.require(:token).permit(:token_name, :location)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/devices/index.html.haml
%h1 Second table
%br/
%table#general-data
  %thead
    %tr
      %th Data
      %th Sensor
      %th Wartość
      %th Nazwa tokenu
      %th Lokalizacja
      %th Okno
      %th 
  %tbody
    - @devices.each do |device|
      %tr
        %td= device.date
        %td= device.sensor
        %td= device.value
        %td= device.token.token_name
        %td= device.token.location
        %td= device.window
        %td= link_to 'Delete', device_path(device), method: :delete, data: { confirm: 'Are you sure?' }   
%br/
= link_to 'Tokens table', tokens_path, "data-no-turbolink" => true
%br/

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Tokens
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield

app/views/tokens/_form.html.haml
= form_for @token do |f|
  %br/
  = f.label :token_name, 'Nazwa tokenu'
  = f.text_field :token_name
  %br/
  = f.label :location, 'Lokalizacja'
  = f.text_field :location
  %br/
  = f.submit 'Zapisz'

app/views/tokens/edit.html.haml
Edit 
= render 'form'
%br/
= link_to 'Back to tokens', tokens_path

app/views/tokens/index.html.haml
= link_to 'sign out', destroy_user_session_path, method: :delete
%br/
%br/  
%h1 Tokens
%table#general-data
  %thead
    %tr
      %th Token
      %th Lokalizacja
      %th
      %th
  %tbody    
    - @tokens.each do |token|
      %tr
        %td= token.token_name
        %td= token.location
        %td= link_to 'Edit', edit_token_path(token)
        %td= link_to 'Delete', token_path(token), method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'new', new_token_path
%br/
%br/
= link_to 'Second table', devices_path, "data-no-turbolink" => true

app/views/tokens/new.html.haml
Add new
= render 'form'
%br/
= link_to 'Back to tokens', tokens_path